# Generated by Django 5.2.1 on 2025-06-11 23:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(help_text='ID do instrutor', primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='Informe o RG do Instrutor', max_length=15)),
                ('nome', models.CharField(help_text='Informe p nome do Instrutor', max_length=100)),
                ('data_nascimento', models.DateField(blank=True, default=datetime.datetime(2025, 6, 11, 23, 57, 48, 515586, tzinfo=datetime.timezone.utc), help_text='Informe a data de nascimento', null=True)),
                ('telefone', models.CharField(help_text='Informe o telefone do Instrutor', max_length=9)),
                ('ddd', models.CharField(help_text='Informe o DDD do Instrutor', max_length=3, null=True)),
                ('codigo_titulo', models.ForeignKey(db_column=' titulo_codigo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos', to='titulo.titulo')),
            ],
        ),
    ]
