# Generated by Django 5.2.1 on 2025-06-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(help_text='Infome o ID do instrutor', primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='Informe o RG do Instrutor', max_length=15)),
                ('nome', models.CharField(help_text=' Informe o nome do instrutor', max_length=70)),
                ('data_Nascimento', models.DateField(verbose_name='Informe a data de nascimento')),
                ('telefone', models.CharField(help_text='Informe o número de telefone', max_length=9)),
                ('ddd', models.CharField(help_text='Informe o DDD', max_length=3)),
            ],
        ),
    ]
