# Generated by Django 5.2.1 on 2025-06-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(help_text='Ente com o numero da matricula do aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do aluno', max_length=100)),
                ('data_incial', models.DateField(verbose_name='Informe a data de inicio do aluno')),
                ('data_final', models.DateField(verbose_name='Informe a data final do aluno')),
            ],
        ),
    ]
