# Generated by Django 5.2.1 on 2025-06-09 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_incial',
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 9, 22, 6, 28, 112964, tzinfo=datetime.timezone.utc), help_text='Informe a data de inicio do aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_final',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 9, 22, 6, 28, 112964, tzinfo=datetime.timezone.utc), help_text='Informe a data final do aluno', null=True),
        ),
    ]
