# Generated by Django 5.2.1 on 2025-06-09 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_remove_aluno_data_incial_aluno_data_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_final',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 9, 22, 8, 41, 906568, tzinfo=datetime.timezone.utc), help_text='Informe a data final do aluno', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 9, 22, 8, 41, 906568, tzinfo=datetime.timezone.utc), help_text='Informe a data de inicio do aluno'),
        ),
    ]
