# Generated by Django 5.2.1 on 2025-06-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('numero', models.AutoField(help_text='Infome o numero da turma', primary_key=True, serialize=False)),
                ('horarioAula', models.TimeField(help_text='Informe o RG do Instrutor')),
                ('duracaoAula', models.SmallIntegerField(help_text=' Informe o nome do instrutor')),
                ('dataInicial', models.DateField(help_text='Informe a data de inicio das aulas')),
                ('dataFinal', models.DateField(help_text='Informe a data final da aulas')),
            ],
        ),
    ]
